/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  assets: {
    Delete: () => import('#controllers/assets/delete_controller'),
    Download: () => import('#controllers/assets/download_controller'),
    List: () => import('#controllers/assets/list_controller'),
    Update: () => import('#controllers/assets/update_controller'),
    Upload: () => import('#controllers/assets/upload_controller'),
  },
  brands: {
    Create: () => import('#controllers/brands/create_controller'),
    Delete: () => import('#controllers/brands/delete_controller'),
    List: () => import('#controllers/brands/list_controller'),
    Retrieve: () => import('#controllers/brands/retrieve_controller'),
    Update: () => import('#controllers/brands/update_controller'),
  },
  complianceChecks: {
    Create: () => import('#controllers/compliance_checks/create_controller'),
    List: () => import('#controllers/compliance_checks/list_controller'),
  },
  guidelines: {
    Retrieve: () => import('#controllers/guidelines/retrieve_controller'),
    Update: () => import('#controllers/guidelines/update_controller'),
  },
}
