/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AssetSchema extends BaseModel {
  static $columns = ['brandId', 'createdAt', 'fileName', 'filePath', 'fileType', 'id', 'tags', 'updatedAt'] as const
  $columns = AssetSchema.$columns
  @column()
  declare brandId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fileName: string
  @column()
  declare filePath: string
  @column()
  declare fileType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare tags: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BrandGuidelineSchema extends BaseModel {
  static $columns = ['bannedWords', 'brandId', 'createdAt', 'id', 'preferredPhrases', 'tone', 'updatedAt'] as const
  $columns = BrandGuidelineSchema.$columns
  @column()
  declare bannedWords: any
  @column()
  declare brandId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare preferredPhrases: any
  @column()
  declare tone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BrandSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = BrandSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ComplianceCheckSchema extends BaseModel {
  static $columns = ['brandId', 'createdAt', 'flaggedInconsistencies', 'id', 'inputText', 'suggestions', 'toneScore'] as const
  $columns = ComplianceCheckSchema.$columns
  @column()
  declare brandId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare flaggedInconsistencies: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare inputText: string
  @column()
  declare suggestions: any
  @column()
  declare toneScore: string
}
